### ISSUE TITLE
Help to convert list

### ISSUE THREAD

**Issue by vaheed** [maravento/blackweb#10]
Hello and thanks for a good job :)

I try to create a blacklist for using in DNSmasq and your list is amazing

can you help how can convert this list with sed or anything to DNSmasq list

this is your list
`.sample.com`

this is a sample of DNSmasq list
`address=/sample.com/0.0.0.0`

**Comment by elico** [comment]
@vaheed with something like a bash script?

**Comment by maravento** [comment]
Blackweb is designed exclusively for Squid-Cache and due to the large number of blocked domains it is not recommended to use it in other environments (DNSMasq, Pi-Hole, Hosts File, etc.), as it could slow down or block your system. Use it at your own risk

Open your linux terminal and run:

For DNSmasq:

`sed -r "s:^\.(.*):address=\1/0.0.0.0:g" blackweb.txt > blackweb_dnsmasq.txt`

For Hosts File:

`sed -r "s:^\.(.*):127.0.0.1 \1:g" blackweb.txt > blackweb_hosts.txt`

or

`sed "s:^\.\(.*\):127.0.0.1 \1:g" blackweb.txt > blackweb_hosts.txt`
