### ISSUE TITLE
URL Patterns and Inconsistency

### ISSUE THREAD

**Issue by drveresh** [maravento/blackweb#17]
I appreciate you if you could clarify for me.

I noticed that out of 4+M total bad sites, 99% of them have got a prefix of some numbers (\d+.*), and 2.7M were hosted on the .blogspot.* domain and all of these could be valid bad links, but in reality, 95% of what (malicious links) I have encountered and what PhishTank and Google security detect are not hosted on .blogspot.* domain and do not have number prefix.  

So, how to treat these two sets and any plan to cover other active malicious database sets in the future?

**Comment by maravento** [comment]
Thank you for using Blackweb

Could you please provide a screenshot or snippet of squid.log or blackweb.txt showing the bug?

Important:
- Blackweb is designed only for squid-cache only. We do not support different use
- Blackweb only collects bad sites from public sources (check [BLOCKLISTS](https://github.com/maravento/blackweb#blocklists)). Therefore you should identify the list that contains the sites that are of concern to you and contact the creator
- All domains included in blackweb are valid. Our method is described in [DNS Lockup](https://github.com/maravento/blackweb#dns-loockup) section

PD: We recommend you a detailed reading of our project so that you can understand what it is about, what it does and what it contains
