### ISSUE TITLE
Source of blockurls.txt

### ISSUE THREAD

**Issue by strilok** [maravento/blackweb#23]
Hi Team,
    Could you please let us know the source for blockurls.txt which you are using in the bwupdate.sh at line 339 :

# add blockurls
sed '/^$/d; /#/d' lst/blockurls.txt | sort -u >>hit.txt

Regards

**Comment by maravento** [comment]
Thank you for your interest in blackweb

Sometimes the [Domain Debugging section](https://github.com/maravento/blackweb#domain-debugging) is not enough to debug all Blackweb errors, since its [SOURCES](https://github.com/maravento/blackweb#sources) are very varied and are in different formats.
This is why we need additional internal debug lists. That is the use of `blockurls.txt` (for malicious domains) and `allowlist.txt` (for exclusions). For example:
If squid produces the following error:
`WARNING: '.foo.blablabla.com' is a subdomain of ' .blablabla.com'`
Then we must include the domain `.blablabla.com` in one of the aforementioned debug lists, depending on whether it is malignant or benign, so that the subdomain `.foo.blablabla.com` is removed from Blackweb during the update.
Regarding your question:
```
# add debug blacklist (This command adds the debug list to the verified domains)
sed '/^$/d; /#/d' lst/debugbl.txt | sort -u >> hit.txt
```
We hope this explanation has been sufficient. We will close the issue, since it has been answered, but if you have another question, you can ask or reopen it

**Comment by maravento** [comment]
the `blockurl.txt` and `allowurls.txt` lists have been renamed, as they are both debugging control lists and not black or white lists per se. This to avoid confusion https://github.com/maravento/blackweb/commit/9a1976335e6bd947cc7e9654a330a129ffe28646
