### ISSUE TITLE
The state of the project is ALPHA, what prevents it from becoming beta or stable?

### ISSUE THREAD

**Issue by elico** [maravento/blackweb#7]
I was wondering: The state of the project is ALPHA, what prevents it from becoming beta or stable?
I would love to have a peek at a check list that can make this project into beta or even stable stage.
I have seen that this project is for Squid-Cache and since I'm maintaining the RPM packages for Squid-Cache it would be fun to try and contribute to this project.
Maybe even package the basic install and update scripts in some way for CentOS and Debian based linux systems?

**Comment by maravento** [comment]
All the information and scripts are available in the repository and its detailed sources in README. Its status is alpha because the scripts are in the correction phase and the sources can change and are subject to constant debugging. Blackweb.txt is an ACL, so it can be used in any GNU / Linux system with Squid-Cache

**Comment by elico** [comment]
@maravento since python is one of the requirements I was thinking about storing the blacklists and whitelist urls in a JSON format instead or in parallel to statically inside the bash script.
This way you can have a list of urls and you can have each list a status such as:
- active(bool)
- enabled(bool)
- format(string)
- id(uint)

Another improvement could be a configuration file that can sit in /etc/blackweb.xyz or /etc/sysconfig/blackweb or /etc/default/blackweb and if exists will be used to set the environmental variables such as "$bl" or maybe the path of the final Blackweb.txt file(Squid-Cache is not obligated to a specific location and the admin can select an alternative).
I also believe that "constant debugging" doesn't force an alpha tag on the project.
A selection of targets in some form like a checklist might help to define the current objectives and achievements that will clear the alpha into beta and\or stable state.
For example:

- [ ] Can be used in any GNU / Linux system with Squid-Cache
 - OS software requirments bash, git, svn, wget, curl, others
 - static standard globally location of the update script(not /etc/init.d/blackweb.sh, maybe /usr/bin/blackweb.sh)
 - Use the /var/blackweb/ as a standard path for temporary or static files like other softwares such as MySQL and many others(can be configurable)
 - Use a lock file to prevent run-time race conditions
- [ ] Can run in a standalone mode that updates and complies the list directly from a selected sources
 - some config file

What do you think about the concepts?

**Comment by maravento** [comment]
All our GNU/Linux projects use scripts in bash, because we consider it to be more appropriate and universal. The included python tools are help to perform a specific activity within the main sequence (in bash) and not vice versa.
As we mentioned earlier, blackweb.txt is an ACL, therefore it is compatible with Squid-Cache (The operating system is not relevant).
The **blackweb.sh** script is **NOT located in /etc/init.d/**. Please read the [README](https://github.com/maravento/blackweb/blob/master/README.md) carefully. Since the last update **blackweb.sh and bwupdate.sh** can be executed from **any location and from any account**.
**blackweb.txt** is in the **alpha** state, because it has not been completely debug, since the external sources that provide the blacklists, described in [README](https://github.com/maravento/blackweb/blob/master/README.md), are not debugged either, therefore it is a very complex work and it requires a long time to reach an other state (beta or stable). 
The contribution that is requested from those interested in this project is described at section [Contributions](https://github.com/maravento/blackweb#contributions) in [README](https://github.com/maravento/blackweb/blob/master/README.md). Also, those interested can contribute to **notify any error** that the project has.

Update: From now on we will no longer handle "states" (alpha, beta, stable)

**Comment by elico** [comment]
@maravento OK, thanks for the detailed response.
I now have seen that there is a change in couple things in the README.
I like the BSD license so I might write a version of similar scripts which licensed with BSD rather then GNU.

**Comment by maravento** [comment]
@elico We understand your concern. The problem is that there are many projects and few personnel, which limits the improvements and expansion. Thank you for your visit
